<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-08-25 14:55

from django.db import migrations, models
=======
# Generated by Django 3.2.20 on 2023-08-25 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> a4bec6620a3b6e25ef7d9d23cfafd69f3adfc33d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> a4bec6620a3b6e25ef7d9d23cfafd69f3adfc33d
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('virtual', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=True)),
                ('ticketPrice', models.FloatField()),
                ('location', models.CharField(max_length=200)),
<<<<<<< HEAD
=======
                ('eventHost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> a4bec6620a3b6e25ef7d9d23cfafd69f3adfc33d
            ],
        ),
    ]
