# Generated by Django 3.2.20 on 2023-08-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('virtual', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=True)),
                ('ticketPrice', models.FloatField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
