<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-08-30 14:47
=======
# Generated by Django 3.2.20 on 2023-08-30 14:32
>>>>>>> LucasSimoes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_category_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
