# Generated by Django 3.2.20 on 2023-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '__first__'),
        ('user', '0003_auto_20230825_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='event.Category'),
        ),
    ]
